#!/usr/bin/env sh

cd
mv .bashrc .bashrc.old
mv .zshrc .zshrc.old
mv .vimrc .vimrc.old
mv .ackrc .ackrc.old
mv .gvimrc .gvimrc.old
mv .emacs .emacs.old
mv .emacs.d .emacs.d.old

ln -s dotfiles/bashrc .bashrc
ln -s dotfiles/zshrc .zshrc
ln -s dotfiles/vim .vim
ln -s dotfiles/vim/vimrc .vimrc
ln -s dotfiles/vim/gvimrc .gvimrc
ln -s dotfiles/ackrc .ackrc
ln -s dotfiles/emacs/emacs.el .emacs
ln -s dotfiles/emacs .emacs.d

touch dotfiles/bash/local
cd -
