#!/usr/bin/env sh

echo "Invading ..."

[ ! -d "$HOME/backups" ] && mkdir "$HOME/backups"
[ ! -d "$HOME/backups/vim_backups" ] && mkdir "$HOME/backups/vim_backups"

cd
echo "Moving existing files to ~/backups ..."
mv .bashrc ~/backups/bashrc.`date +%s`
mv .vimrc ~/backups/vimrc.`date +%s`
mv .vim ~/backups/vim.`date +%s`
mv .ackrc ~/backups/ackrc.`date +%s`
mv .gvimrc ~/backups/gvimrc.`date +%s`

ln -s dotfiles/bashrc .bashrc
ln -s dotfiles/vim .vim
ln -s dotfiles/vim/vimrc .vimrc
ln -s dotfiles/vim/gvimrc .gvimrc
ln -s dotfiles/ackrc .ackrc

touch dotfiles/bash/local
echo "Done !"
