source ~/.bashrc

# settings
autoload -U colors && colors
autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit
autoload -Uz vcs_info

# vcs_info
zstyle ':vcs_info:*' actionformats '%F{242}%s%f:%F{111}%b%f'
zstyle ':vcs_info:*' formats '%F{242}%s%f:%F{111}%b%f'
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'

zstyle ':completion:*' menu select

export SAVEHIST=50000
export HISTSIZE=50000
export HISTFILE=~/.zsh_history

setopt prompt_subst
setopt inc_append_history
setopt share_history

fpath=($HOME/dotfiles/extern/zsh-completions/src $fpath)

if which _dotfiles_scm_info &>/dev/null; then
  VCS_CMD='$(_dotfiles_scm_info)'
else
  precmd() {
    vcs_info
  }
  VCS_CMD=' ${vcs_info_msg_0_}'
fi

PROMPT='\
%B%F{075}%n@%m%f%b%F{10}:%f%F{251}%~%f'${VCS_CMD}' %(?..%F{161}[%?] )\

λ%f '


# Fish-style up/down arrows history search
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# Help command
autoload -Uz run-help
autoload -Uz run-help-git
autoload -Uz run-help-svn
autoload -Uz run-help-svk
unalias run-help
alias help=run-help

# bindings
bindkey '^R' 'history-incremental-search-backward'
