"gui
if has('gui_macvim')
    " Fullscreen takes up entire screen
    set fuoptions=maxhorz,maxvert
    set guifont=Monaco:h11

    " Command-Return for fullscreen
    macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>
    map <D-F> :Ack<space>

    " Start without the toolbar
    set guioptions=aAce

    color slate2
endif

