#!/usr/bin/env ruby

BUNDLE_DIR = File.expand_path('../bundle', __FILE__)
BUNDLE_FILE = File.expand_path('../bndls.txt', __FILE__)

def main
  build_flag   = ARGV.include?('--build') || ARGV.include?('--build-only')
  install_flag = !ARGV.include?('--build-only')

  if install_flag
    # Fetch and install
    File.open(BUNDLE_FILE, "r") do |infile|
      until infile.eof?
        install infile.gets
      end
    end
  end

  return unless build_flag

  # Build extensions (extconf.rb)
  pattern = File.join(BUNDLE_DIR, "*", "ruby", "*", "extconf.rb")
  Dir.glob(pattern).each do |path|
    path.slice!(%r,/([^/]*)$,)
    cd(path) do
      puts "> Building #{path}"
      %x{ ruby extconf.rb }
      %x{ make }
    end
  end

  # Build install.sh
  pattern = File.join(BUNDLE_DIR, "*", "install.sh")
  Dir.glob(pattern).each do |path|
    path.slice!(%r,/([^/]*)$,)
    cd(path) do
      puts "> Building #{path}"
      %x{ bash install.sh --clang-completer }
    end
  end
end

require 'fileutils'
include FileUtils

METHODS = {
  :github => /github\.com/,
  :vim => /download_script/,
  :bitbucket => /bitbucket\./
}

CMDZ = {
  git: {
    pull: 'git pull',
    clone: 'git clone',
    validate: lambda {|url| url.gsub(/^http/, 'git')},
  },
  mercurial: {
    pull: 'hg pull',
    clone: 'hg clone',
  }
}

def install(line)
  line.strip!

  if line.empty? or line[0] == "#"
    return
  end

  # call corresponding method according to url pattern
  METHODS.each do |meth, regex|
    send meth, line if regex =~ line
  end
end

def github line
  install_scm :git, line
end

def bitbucket line
  install_scm :mercurial, line
end

def install_scm scm, line
  raise "SCM not found" unless CMDZ.has_key? scm

  re = %r,/([^/]*)$,
  name = line[re, 1]
  url = line

  path = File.expand_path(name, BUNDLE_DIR)

  # pull if repo already exists
  if File.exists?(path)
    puts "> Pulling #{url}"
    cd(path) { %x{ #{CMDZ[scm][:pull]} } }
    return
  end

  if validate = CMDZ[scm][:validate]
    url = validate.call(url)
  end

  puts "> Cloning #{url}"
  %x{ #{CMDZ[scm][:clone]} #{url} #{path} }
end

def vim line
  line =~ /#/ or raise SyntaxError, "FATAL: No name found in #{line}!"

  re = /^(.*)#(.*)#(.*)$/
  url  = line[re, 1]
  name = line[re, 2]
  type = line[re, 3]

  path = File.expand_path("#{name}/#{type}/#{name}.vim", BUNDLE_DIR)
  unless File.exists? path
    puts "> Downloading #{url}"
    %x, curl -s -o #{path} --create-dirs #{url}` ,
  end
end

main
