;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        evil-insert
        evil-normal-state
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-newline
        coffee-newline-and-indent
        describe-key
        eval-expression
        evil-backward-char
        evil-forward-char
        evil-forward-word-begin
        evil-next-line
        evil-previous-line
        evil-ret
        evil-search-next
        ))
