#!/usr/bin/env bash

# general
alias ls='ls -p -G'
alias ll='ls -l -h'
alias blt="vim $HOME/dotfiles/bash; source $HOME/dotfiles/bashrc"
alias t250='tail -n250'
alias xee='open -a xee'
alias findswp='find . -name "*.swp"'
alias rmswp='find . -name "*.swp" -exec rm {} \;'
alias vi='vim --noplugin'
alias notes='vim ~/notes.md'
alias hosts='sudo vim /etc/hosts'
alias flushcache='dscacheutil -flushcache'

# git
alias g='git status'
alias gst='git status'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gca='git commit -a'
alias gcaa='git commit -a --amend -C HEAD'
alias gg='git grep'
alias glo='git log'
alias gl='git pull'
alias gp='git push'

# ruby
alias ss='script/server'
alias sg='shotgun --host 0.0.0.0 config.ru'
alias sgbg='shotgun --host 0.0.0.0 config.ru &> /dev/null &'
alias b='bundle exec'
alias reindex='rails runner script/reindex.rb'
alias rb='rbenv'
alias rbrh='rbenv rehash'
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
alias remove_all_gems='gem list | cut -d" " -f1 | xargs gem uninstall -aIx'
alias rvmrc='rvm rvmrc'
alias r='rvm default do'
alias ng-serverjruby='JRUBY_OPTS="" jruby --ng-server'

# python
alias p='python'
alias json='python -m json.tool'

# java
alias javassert='java -enableassertions'
alias tcpmon='java org.apache.axis.utils.tcpmon'
alias adminclient='java org.apache.axis.client.AdminClient'
alias javaproxy='java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8080'
alias eclimd='$ECLIPSE_HOME/eclimd'

# php
alias sf='php symfony'
alias sf2='php app/console'

# coffeescript
alias coffeec='find . -name "*.coffee" | xargs coffee -w -c'

function uri () {
    echo $1 | ruby -p -e 'require "uri";$_=URI.encode($_.strip)'
}
