#!/usr/bin/env bash

# general
alias ls='ls -p -G'
alias ll='ls -l'
alias blt="vim $HOME/dotfiles/bash; source $HOME/dotfiles/bashrc"
alias t250='tail -n250'
alias xee='open -a xee'

# git
alias g='git status'
alias gst='git status'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gca='git commit -a'
alias gcaa='git commit -a --amend -C HEAD'
alias gg='git grep'
alias glo='git log'
alias gl='git pull'
alias gp='git push'

# php
alias sf='php symfony'
alias sf2='php app/console'

# ruby
alias ss='script/server'
alias sg='shotgun --host 0.0.0.0 config.ru'
alias gotogem="cd $GEM_HOME/gems"
alias be='bundle exec'
alias reindex='rails runner script/reindex.rb'

# python
alias p='python'

# java
alias javassert='java -enableassertions'
alias tcpmon='java org.apache.axis.utils.tcpmon'
alias adminclient='java org.apache.axis.client.AdminClient'
alias javap='java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8080'

# coffeescript
alias coffeec='find . -name "*.coffee" | xargs coffee -w -c'
